spring.application.name=tienda

#para definir el puerto donde escucha el servidor
server.port=80

#se define el formato de despliegue de fecha/hora en el log
logging.pattern.dateformat=hh:mm

#para eliminar el banner de spring al inicio
spring.main.banner-mode=off

#evitar el uso de cache en desarrollo... en produccion SI
spring.thymeleaf.cache=false